### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by n8chur** [AttilaTheFun/SwaggerParser#1]
Have you considered [adding a license to this repository](https://help.github.com/articles/adding-a-license-to-a-repository/)?

I was hoping to use (and likely contribute to) this package to parse swagger documents for my project.

Thanks!

**Comment by AttilaTheFun** [comment]
@n8chur - I don't know why I didn't get a notification about your issue before. I'd love to add a license! Would MIT be good?

**Comment by AttilaTheFun** [comment]
Ok I added the MIT license. I was planning on adding a license and a readme when I felt the library had reached a '1.0' state but if you folks want to start using it and contributing back, by all means do!
