### ISSUE TITLE
AllOf

### ISSUE THREAD

**Issue by yonaskolb** [AttilaTheFun/SwaggerParser#2]
Hey, any chance of getting `allOff` support, to enable inheritance?
http://swagger.io/specification

**Comment by n8chur** [comment]
I have a private fork that's nearly ready to go public with:
- `allOf` support
- `discrminator` support
- `x-abstract` support
- `x-nullable` support
- `Metadata` on references
- References to model files in relative paths
- Additional unit tests

`x-abstract` declares that a definition is purely an interface and not a concrete model. This works hand in hand with `allOf` and `discrminator` to create polymorphic model descriptions. Generally `x-abstract` definitions also have a `discrminator`, but it could be useful if you wanted to codegen shared interfaces between model objects.

The main issue blocking my fork from becoming public is [my open issue regarding a license file](https://github.com/AttilaTheFun/SwaggerParser/issues/1). I'd also like to submit a PR if @AttilaTheFun approves of the path I went down.

**Comment by yonaskolb** [comment]
Nice work @n8chur!
Maybe @AttilaTheFun hasn't seen these messages yet, as he's not watching the repo

**Comment by AttilaTheFun** [comment]
@n8chur @yonaskolb Oh, cool! I can add a license this afternoon! I don't care which one. MIT? GPL? Apache? Once I do that do you want to make a PR? I'm happy to review it.

**Comment by AttilaTheFun** [comment]
Ok I added the MIT license. Would you like to create a PR?

**Comment by n8chur** [comment]
Thanks, @AttilaTheFun! I'll get a PR ready asap.

**Comment by AttilaTheFun** [comment]
Awesome! I'm working on a code generator library that consumes this as well. I'm excited to see what you make with it!

**Comment by n8chur** [comment]
Nice! 

I'm also working on a Go model generator, as well as a test fixture generator. These test fixtures (similar to cassettes with a request and response combination defined in each fixture) could be used to write unit tests against a Swagger specification. 

I'll be sure to show my work once it's ready!

**Comment by AttilaTheFun** [comment]
Sweet :)
My code gen library already does some Go model generation if you want to check it out:
https://github.com/AttilaTheFun/SwaggerCodeGenerator
It's still a bit of a mess, though. I'm still iterating on / refactoring it.

**Comment by AttilaTheFun** [comment]
@yonaskolb @n8chur I created a PR to add the allOf support here:
https://github.com/AttilaTheFun/SwaggerParser/pull/4

Would you like to review it and tell me if it suits your needs?

**Comment by n8chur** [comment]
I got my PR up with the described changes: https://github.com/AttilaTheFun/SwaggerParser/pull/5

**Comment by n8chur** [comment]
I closed #5 and opened a new PR with just [`allOf` support (#6)](https://github.com/AttilaTheFun/SwaggerParser/pull/6)

I'll add the rest of the functionality as follow-up PRs.

**Comment by yonaskolb** [comment]
Just so you know guys, my version of a code generator can be found here https://github.com/yonaskolb/SwagGen
I should probably create a Go template as well just for laughs :)

I'm probably going to move the Swagger framework over to this library as it's a bit more strict, and mine doesn't handle some edge cases

**Comment by AttilaTheFun** [comment]
@n8chur @yonaskolb Thanks so much you guys! I just merged @n8chur's pull request with the allOf support and tagged it as '0.3.0'. @yonaskolb Does this do everything you need? If so I'll close out the ticket. @n8chur Would you like to open a separate PR or pr(s) for your added support for:
```
discrminator support
x-abstract support
x-nullable support
Metadata on references
References to model files in relative paths
```

**Comment by yonaskolb** [comment]
I believe that's all I need. I'll have to see while doing the actual integration if there are any missing pieces 👍

**Comment by AttilaTheFun** [comment]
Ok @yonaskolb I'm gonna close this issue then but please feel free to create another issue if you encounter any more missing pieces when integrating it :)
