### ISSUE TITLE
Recursive references

### ISSUE THREAD

**Issue by yonaskolb** [AttilaTheFun/SwaggerParser#20]
There's an issue at the moment where if there is a circular reference within schemas via references, then SwaggerParser crashes due to infinite recursion. eg `schema1` references `schema2` which in turn references `schema1`

**Comment by AttilaTheFun** [comment]
Ah, yeah, I see how that could be a problem :(
I'll address it on your PR.

**Comment by AttilaTheFun** [comment]
(Copied from PR comment)

So, I built this library specifically to work with Golang and Swift.
More specifically, I wanted it to work with value types. 
Even though JSON Schema works with recursive type declarations, 
that could only ever work in a dynamic language or with reference types.

In Javascript, everything is an object and every object is a hashmap. As such, there is no need
to know the memory layout for a type at compile time. But in Swift and Go, recursive (value) type
references are actually compile-time errors. Golang doesn't even support non-value types.

As such, I'm going to close this issue. I would rather enforce the behavior in this library than place that responsibility on consumers to work around. If you need recursive references for some reason, feel free to keep your fork and rebase it off of master as necessary. Thanks!
