### ISSUE TITLE
Schemes not decoded

### ISSUE THREAD

**Issue by yonaskolb** [AttilaTheFun/SwaggerParser#21]
Schemes aren't being decoded properly due to lack of automatic conversion of `[RawRepresentable]` types in `ObjectMapper`

**Comment by AttilaTheFun** [comment]
Could you give an example of what you're talking about? Will this issue be resolved by the migration to Codable in Swift 4?

**Comment by yonaskolb** [comment]
I mean that this line doesn't work:
https://github.com/AttilaTheFun/SwaggerParser/blob/master/Sources/Swagger.swift#L96
If you command click though to the map function, you can see it's using the function that return T which is just one that casts to the expected type.

This would be fixed by Codable it supports decoding [RawRepresentable] automatically.

It could be fixed here by just doing the decoding in parts as well.

**Comment by AttilaTheFun** [comment]
Okay I pushed a commit to decode it first into an array of strings and then map it into the enum. When swift 4 is released and I rip out ObjectMapper in favor of Codable I can remove that code as well.
