### ISSUE TITLE
Improve DecodingError Granularity

### ISSUE THREAD

**Issue by n8chur** [AttilaTheFun/SwaggerParser#28]
Currently `DecodingError` is used in many places without any more specific context which makes it very difficult to track down decoding issues.

It would be great to have a more specific message regarding what went wrong (including things like model names, whether it's related to a path, etc.) when a DecodingError is thrown.

**Comment by AttilaTheFun** [comment]
Yeah, you're absolutely right. I should add a string description, file, and line number.

**Comment by AttilaTheFun** [comment]
@n8chur Okay I pushed https://github.com/AttilaTheFun/SwaggerParser/commit/2e68467558cf15e89d6516aec1bea18f2639de66
Which augments DecodingError with a localizedDescription, file and line number. It will be included in 0.4.0

**Comment by n8chur** [comment]
@AttilaTheFun: Nice! Thanks! That should be extremely helpful for debugging decoding issues 👍
