### ISSUE TITLE
Version 0.4.0

### ISSUE THREAD

**Issue by AttilaTheFun** [AttilaTheFun/SwaggerParser#29]
I just went through and did a bunch of cleanup on the library's public API in preparation for 0.4.0:
<img width="992" alt="screen shot 2017-07-12 at 1 26 10 am" src="https://user-images.githubusercontent.com/3255391/28108701-464094e4-66a1-11e7-96ae-e5440959605c.png">

@n8chur @yonaskolb Would you like to look over the changes and let me know if there are any other API-breaking changes you think we need before I create a v0.4.0 release?

**Comment by yonaskolb** [comment]
Looks good. Though not sure that `operation.securityRequirements` should be optional, as an empty array and no array are semantically different in swagger, as per the doc comment

**Comment by n8chur** [comment]
@AttilaTheFun LGTM 👍

**Comment by AttilaTheFun** [comment]
@yonaskolb, ah good point. I forgot about that. If you have top-level security requirements, an empty array removes them, while nil would defer to the top-level requirements if any.

**Comment by AttilaTheFun** [comment]
Okay, I cut version 0.4.0 here:
https://github.com/AttilaTheFun/SwaggerParser/releases/tag/0.4.0

Thanks for all your help @n8chur and @yonaskolb!
Feel fee to keep filing issues and sending PRs if you have / find any other issues.
