### ISSUE TITLE
Response headers should parse `x-example` instead of `example`

### ISSUE THREAD

**Issue by n8chur** [AttilaTheFun/SwaggerParser#35]
`example` is not a valid response header object so the parser should look for `x-example` instead.

**Comment by AttilaTheFun** [comment]
Hey @n8chur thanks for filing an issue. I don't have time to work on this right now, but if you wanna make a small PR for that change I can happily review + accept it.

**Comment by AttilaTheFun** [comment]
Fixed in https://github.com/AphelionApps/SwaggerParser/releases/tag/0.6.2

**Comment by n8chur** [comment]
Thanks!
