### ISSUE TITLE
Create README.txt

### ISSUE THREAD

**Issue by AttilaTheFun** [AttilaTheFun/SwaggerParser#7]
In order to reach '1.0' status, I want to resolve all of the major outstanding issues and complete the Codable refactor. I was hesitant to create a readme while the API was very much in flux. Once the API has stabilized I want to create better documentation in the form of a readme file and https://github.com/realm/jazzy docs hosted on the repo's GitHub.io page. @n8chur @yonaskolb does that sound reasonable?

**Comment by AttilaTheFun** [comment]
Added README.md

**Comment by yonaskolb** [comment]
Sounds good 👍
